### ISSUE TITLE
HowTo install and use jargon2 WITHOUT Marven rep.

### ISSUE THREAD

**Issue by Darlio** [kosprov/jargon2-backends#1]
Hello,

I am writing a HowTo on Jargon2.

After importing both JARs in my project (jargon2-api-1.1.1.jar & jargon2-native-ri-backend-1.1.1.jar)...
I am using this code to "try" an easy hsashing :

`
public  void hashMe() {
		        byte[] password = "this is a password".getBytes();

		        // Configure the hasher
		        Hasher hasher = jargon2Hasher()
		                .type(Type.ARGON2d) // Data-dependent hashing
		                .memoryCost(65536)  // 64MB memory cost
		                .timeCost(3)        // 3 passes through memory
		                .parallelism(4)     // use 4 lanes and 4 threads
		                .saltLength(16)     // 16 random bytes salt
		                .hashLength(16);    // 16 bytes output hash

		        // Set the password and calculate the encoded hash
		        String encodedHash = hasher.password(password).encodedHash();

		        System.out.printf("Hash: %s%n", encodedHash);

		        // Just get a hold on the verifier. No special configuration needed
		        Verifier verifier = jargon2Verifier();

		        // Set the encoded hash, the password and verify
		        boolean matches = verifier.hash(encodedHash).password(password).verifyEncoded();

		        System.out.printf("Matches: %s%n", matches);
		    
		
		String newHash = "";
		//newHash = PasswordHasher.encodedHash(hashIt.toCharArray());
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "Hashed string is '", newHash)); // To be passed to log		
}

`

And this is the resulting ERROR I get : 
`
java.util.ServiceConfigurationError: com.kosprov.jargon2.spi.Jargon2Backend: Provider com.kosprov.jargon2.nativeri.backend.NativeRiJargon2Backend could not be instantiated
`

What am I missing ?

Best regards,

Darlio...

**Comment by kosprov** [comment]
Hello.

Thanks for trying Jargon2.

`jargon2-native-ri-backend` has a transitive dependency to `jargon2-native-ri-binaries-generic` which contains the actual native code,  and JNA for invoking the native code, which has its own transitive dependencies and so on.

Maven adds those dependencies automatically. When you set your classpath manually, you have to resolve the whole dependency tree by hand.

You can use `mvn dependency:tree` as per https://stackoverflow.com/questions/3342908/how-to-get-a-dependency-tree-for-an-artifact to see what jars you're missing.

If you're packaging a WAR, make sure all these jars are in WEB-INF/lib.

**Comment by Darlio** [comment]
Hello,

Thank you for your help !

I did add the jargon2-native-ri-binaries-generic (v1.1.1) JAR in the
ClassPath.
https://user-images.githubusercontent.com/32061339/44165976-76b1c580-a0ca-11e8-928a-c5c37390c7c4.jpg

But still have this same error.

The code I use is this one :
------------
`
public  void hashMe() {
        byte[] password = "this is a password".getBytes();

        // Configure the hasher
        Hasher hasher = jargon2Hasher()
                .type(Type.ARGON2d) // Data-dependent hashing
                .memoryCost(65536)  // 64MB memory cost
                .timeCost(3)        // 3 passes through memory
                .parallelism(4)     // use 4 lanes and 4 threads
                .saltLength(16)     // 16 random bytes salt
                .hashLength(16);    // 16 bytes output hash

        // Set the password and calculate the encoded hash
        String encodedHash = hasher.password(password).encodedHash();
        System.out.printf("Hash: %s%n", encodedHash);

        // Just get a hold on the verifier. No special configuration needed
        Verifier verifier = jargon2Verifier();

        // Set the encoded hash, the password and verify
        boolean matches =
verifier.hash(encodedHash).password(password).verifyEncoded();
        System.out.printf("Matches: %s%n", matches);

String newHash = "";
//newHash = PasswordHasher.encodedHash(hashIt.toCharArray());
FacesContext.getCurrentInstance().addMessage(null, new
FacesMessage(FacesMessage.SEVERITY_WARN, "Hashed string is '", newHash));
// To be passed to log
}
`
------------

Here is the complete CONSOLE stack trace lines :
------------ WHEN SERVER IS STARTED :
15-Aug-2018 10:30:47.767 WARNING [main]
org.apache.tomcat.util.digester.SetPropertiesRule.begin
[SetPropertiesRule]{Server/Service/Engine/Host/Context} Setting property
'source' to 'org.eclipse.jst.jee.server:axiomInvoice' did not find a
matching property.
15-Aug-2018 10:30:47.773 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Server version:
  Apache Tomcat/9.0.8
15-Aug-2018 10:30:47.774 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Server built:
  Apr 27 2018 19:32:00 UTC
15-Aug-2018 10:30:47.774 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Server number:
 9.0.8.0
15-Aug-2018 10:30:47.774 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log OS Name:
 Windows 10
15-Aug-2018 10:30:47.774 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log OS Version:
  10.0
15-Aug-2018 10:30:47.774 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Architecture:
  amd64
15-Aug-2018 10:30:47.774 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Java Home:
 C:\Program Files\Java\jre1.8.0_171
15-Aug-2018 10:30:47.775 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log JVM Version:
 1.8.0_171-b11
15-Aug-2018 10:30:47.775 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:
  Oracle Corporation
15-Aug-2018 10:30:47.775 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:
 C:\Users\daric.lion\eclipse-workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
15-Aug-2018 10:30:47.775 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:
 C:\_AxiomFacturation\apache-tomcat-9.0.8
15-Aug-2018 10:30:47.775 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Command line
argument:
-agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:52341
15-Aug-2018 10:30:47.775 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Command line
argument:
-javaagent:C:\Users\daric.lion\jee-latest\eclipse\configuration\org.eclipse.osgi\1795\0\.cp\lib\javaagent-shaded.jar
15-Aug-2018 10:30:47.775 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Command line
argument:
-Dcatalina.base=C:\Users\daric.lion\eclipse-workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
15-Aug-2018 10:30:47.776 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Command line
argument: -Dcatalina.home=C:\_AxiomFacturation\apache-tomcat-9.0.8
15-Aug-2018 10:30:47.776 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Command line
argument:
-Dwtp.deploy=C:\Users\daric.lion\eclipse-workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps
15-Aug-2018 10:30:47.776 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Command line
argument:
-Djava.endorsed.dirs=C:\_AxiomFacturation\apache-tomcat-9.0.8\endorsed
15-Aug-2018 10:30:47.776 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Command line
argument:
-Djava.util.logging.config.file=C:\Users\daric.lion\eclipse-workspace\Servers\logging.properties
15-Aug-2018 10:30:47.776 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Command line
argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
15-Aug-2018 10:30:47.778 INFO [main]
org.apache.catalina.startup.VersionLoggerListener.log Command line
argument: -Dfile.encoding=UTF-8
15-Aug-2018 10:30:47.779 INFO [main]
org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR
based Apache Tomcat Native library [1.2.16] using APR version [1.6.3].
15-Aug-2018 10:30:47.779 INFO [main]
org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR
capabilities: IPv6 [true], sendfile [true], accept filters [false], random
[true].
15-Aug-2018 10:30:47.779 INFO [main]
org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL
configuration: useAprConnector [false], useOpenSSL [true]
15-Aug-2018 10:30:48.840 INFO [main]
org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL
successfully initialized [OpenSSL 1.0.2m  2 Nov 2017]
15-Aug-2018 10:30:48.983 INFO [main]
org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler
["http-nio-8070"]
15-Aug-2018 10:30:54.017 INFO [main]
org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared
selector for servlet write/read
15-Aug-2018 10:30:54.029 INFO [main]
org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler
["ajp-nio-8079"]
15-Aug-2018 10:30:54.031 INFO [main]
org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared
selector for servlet write/read
15-Aug-2018 10:30:54.031 INFO [main]
org.apache.catalina.startup.Catalina.load Initialization processed in 6847
ms
15-Aug-2018 10:30:54.073 INFO [main]
org.apache.catalina.core.StandardService.startInternal Starting service
[Catalina]
15-Aug-2018 10:30:54.073 INFO [main]
org.apache.catalina.core.StandardEngine.startInternal Starting Servlet
Engine: Apache Tomcat/9.0.8
15-Aug-2018 10:30:57.297 INFO [main]
org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned
for TLDs yet contained no TLDs. Enable debug logging for this logger for a
complete list of JARs that were scanned but no TLDs were found in them.
Skipping unneeded JARs during scanning can improve startup time and JSP
compilation time.
15-Aug-2018 10:31:02.354 INFO [main]
org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned
for TLDs yet contained no TLDs. Enable debug logging for this logger for a
complete list of JARs that were scanned but no TLDs were found in them.
Skipping unneeded JARs during scanning can improve startup time and JSP
compilation time.
15-Aug-2018 10:31:02.436 INFO [main]
org.jboss.weld.environment.servlet.EnhancedListener.onStartup
WELD-ENV-001008: Initialize Weld using ServletContainerInitializer
15-Aug-2018 10:31:02.483 INFO [main]
org.jboss.weld.bootstrap.WeldStartup.<clinit> WELD-000900: 3.0.4 (Final)
15-Aug-2018 10:31:02.682 INFO [main]
org.jboss.weld.environment.deployment.discovery.ReflectionDiscoveryStrategy.processAnnotatedDiscovery
WELD-ENV-000014: Falling back to Java Reflection for
bean-discovery-mode="annotated" discovery. Add org.jboss:jandex to the
classpath to speed-up startup.
15-Aug-2018 10:31:02.947 INFO [main]
org.jboss.weld.bootstrap.WeldStartup.startContainer WELD-000101:
Transactional services not available. Injection of @Inject UserTransaction
not available. Transactional observers will be invoked synchronously.
15-Aug-2018 10:31:03.384 WARN [main]
org.jboss.weld.bootstrap.events.BeforeBeanDiscoveryImpl.addAnnotatedType
WELD-000146: BeforeBeanDiscovery.addAnnotatedType(AnnotatedType<?>) used
for class com.sun.faces.flow.FlowDiscoveryCDIHelper is deprecated from CDI
1.1!
15-Aug-2018 10:31:03.479 INFO [main]
org.jboss.weld.environment.tomcat.TomcatContainer.initialize
WELD-ENV-001100: Tomcat 7+ detected, CDI injection will be available in
Servlets, Filters and Listeners.
15-Aug-2018 10:31:03.905 INFO [main]
com.sun.faces.config.ConfigureListener.contextInitialized Initializing
Mojarra 2.4.0 for context '/axiomInvoice'
15-Aug-2018 10:31:04.111 INFO [main]
com.sun.faces.spi.InjectionProviderFactory.createInstance JSF1048:
PostConstruct/PreDestroy annotations present.  ManagedBeans methods marked
with these annotations will have said annotations processed.
15-Aug-2018 10:31:05.387 INFO [main]
com.sun.faces.config.ConfigureListener$WebConfigResourceMonitor$Monitor.<init>
Monitoring
file:/C:/Users/daric.lion/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/axiomInvoice/WEB-INF/faces-config.xml
for modifications
15-Aug-2018 10:31:05.479 INFO [main]
org.primefaces.webapp.PostConstructApplicationEventListener.processEvent
Running on PrimeFaces 6.2
15-Aug-2018 10:31:05.483 INFO [main]
com.sun.faces.config.ConfigureListener.contextInitialized Initializing
Mojarra 2.4.0 for context '/axiomInvoice'
15-Aug-2018 10:31:05.561 INFO [main]
com.sun.faces.spi.InjectionProviderFactory.createInstance JSF1048:
PostConstruct/PreDestroy annotations present.  ManagedBeans methods marked
with these annotations will have said annotations processed.
15-Aug-2018 10:31:05.730 INFO [main]
com.sun.faces.config.ConfigureListener$WebConfigResourceMonitor$Monitor.<init>
Monitoring
file:/C:/Users/daric.lion/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/axiomInvoice/WEB-INF/faces-config.xml
for modifications
15-Aug-2018 10:31:05.734 INFO [main]
org.primefaces.webapp.PostConstructApplicationEventListener.processEvent
Running on PrimeFaces 6.2
15-Aug-2018 10:31:05.735 INFO [main]
org.primefaces.webapp.PostConstructApplicationEventListener.processEvent
Running on PrimeFaces 6.2
15-Aug-2018 10:31:05.764 INFO [main]
org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler
["http-nio-8070"]
15-Aug-2018 10:31:05.776 INFO [main]
org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler
["ajp-nio-8079"]
15-Aug-2018 10:31:05.779 INFO [main]
org.apache.catalina.startup.Catalina.start Server startup in 11747 ms



------------ WHEN EXECUTING THIS HIGHLIGHTED CODE (in debug mode) :
https://user-images.githubusercontent.com/32061339/44165914-48cc8100-a0ca-11e8-836a-2b27819c604d.jpg

I do get a this thrown as error :
https://user-images.githubusercontent.com/32061339/44166198-0fe0dc00-a0cb-11e8-93c2-1c730777d8c1.jpg


Resulting in these CONSOLE stack trace lines :
15-Aug-2018 10:40:32.380 WARNING [http-nio-8070-exec-8]
com.sun.faces.lifecycle.InvokeApplicationPhase.execute #{LoginBean.hashMe}:
java.util.ServiceConfigurationError:
com.kosprov.jargon2.spi.Jargon2Backend: Provider
com.kosprov.jargon2.nativeri.backend.NativeRiJargon2Backend could not be
instantiated
 javax.faces.FacesException: #{LoginBean.hashMe}:
java.util.ServiceConfigurationError:
com.kosprov.jargon2.spi.Jargon2Backend: Provider
com.kosprov.jargon2.nativeri.backend.NativeRiJargon2Backend could not be
instantiated
at
com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:120)
at
com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:95)
at
org.primefaces.application.DialogActionListener.processAction(DialogActionListener.java:46)
at javax.faces.component.UICommand.broadcast(UICommand.java:246)
at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:871)
at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1419)
at
com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:82)
at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:731)
at javax.faces.webapp.FacesServlet.service(FacesServlet.java:475)
at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at
org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:412)
at
org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at
org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
at
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1385)
at
org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Unknown Source)
Caused by: javax.faces.el.EvaluationException:
java.util.ServiceConfigurationError:
com.kosprov.jargon2.spi.Jargon2Backend: Provider
com.kosprov.jargon2.nativeri.backend.NativeRiJargon2Backend could not be
instantiated
at
com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:100)
at
com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:106)
... 32 more
Caused by: java.util.ServiceConfigurationError:
com.kosprov.jargon2.spi.Jargon2Backend: Provider
com.kosprov.jargon2.nativeri.backend.NativeRiJargon2Backend could not be
instantiated
at java.util.ServiceLoader.fail(Unknown Source)
at java.util.ServiceLoader.access$100(Unknown Source)
at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
at java.util.ServiceLoader$1.next(Unknown Source)
at
com.kosprov.jargon2.internal.discovery.Jargon2BackendDiscovery.getJargon2Backend(Jargon2BackendDiscovery.java:57)
at com.kosprov.jargon2.internal.HasherImpl.<init>(HasherImpl.java:18)
at com.kosprov.jargon2.api.Jargon2.jargon2Hasher(Jargon2.java:470)
at com.axiominvoice.web.app.beans.LoginBean.hashMe(LoginBean.java:447)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
at
org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
at
org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
at
com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:89)
at
com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:90)
... 33 more
Caused by: java.lang.NoClassDefFoundError: com/sun/jna/Pointer
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
at java.lang.Class.getConstructor0(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
... 50 more
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Pointer
at
org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1292)
at
org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1121)
... 54 more

15-Aug-2018 10:40:32.391 SEVERE [http-nio-8070-exec-8]
com.sun.faces.context.AjaxExceptionHandlerImpl.handlePartialResponseError
javax.faces.el.EvaluationException: java.util.ServiceConfigurationError:
com.kosprov.jargon2.spi.Jargon2Backend: Provider
com.kosprov.jargon2.nativeri.backend.NativeRiJargon2Backend could not be
instantiated
at
com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:100)
at
com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:106)
at
com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:95)
at
org.primefaces.application.DialogActionListener.processAction(DialogActionListener.java:46)
at javax.faces.component.UICommand.broadcast(UICommand.java:246)
at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:871)
at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1419)
at
com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:82)
at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:731)
at javax.faces.webapp.FacesServlet.service(FacesServlet.java:475)
at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at
org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:412)
at
org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at
org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
at
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1385)
at
org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Unknown Source)
Caused by: java.util.ServiceConfigurationError:
com.kosprov.jargon2.spi.Jargon2Backend: Provider
com.kosprov.jargon2.nativeri.backend.NativeRiJargon2Backend could not be
instantiated
at java.util.ServiceLoader.fail(Unknown Source)
at java.util.ServiceLoader.access$100(Unknown Source)
at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
at java.util.ServiceLoader$1.next(Unknown Source)
at
com.kosprov.jargon2.internal.discovery.Jargon2BackendDiscovery.getJargon2Backend(Jargon2BackendDiscovery.java:57)
at com.kosprov.jargon2.internal.HasherImpl.<init>(HasherImpl.java:18)
at com.kosprov.jargon2.api.Jargon2.jargon2Hasher(Jargon2.java:470)
at com.axiominvoice.web.app.beans.LoginBean.hashMe(LoginBean.java:447)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
at
org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
at
org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
at
com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:89)
at
com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:90)
... 33 more
Caused by: java.lang.NoClassDefFoundError: com/sun/jna/Pointer
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
at java.lang.Class.getConstructor0(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
... 50 more
Caused by: java.lang.ClassNotFoundException: com.sun.jna.Pointer
at
org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1292)
at
org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1121)
... 54 more


Do you have enough info to help me out ?

Thanks a lot for your time and energy on this one !!! I will be writing a
"HowTo" inside our company about this implementation of Argon2 which will
be our standard ;-) !

All the very best to you,

Regards,

Daric

**Comment by kosprov** [comment]
Running `mvn dependency:tree` lists 3 additional jars for JNA and  jnaerator runtime.

- `com.nativelibs4java:jnaerator-runtime:jar:0.12`
- `com.nativelibs4java:ochafik-util:jar:0.12`
- `net.java.dev.jna:jna:jar:4.1.0`

Make sure you package all of them in your WAR.

    $ mvn dependency:tree -Dscope=runtime
    [INFO] Scanning for projects...
    [INFO] Inspecting build with total of 1 modules...
    [INFO] Installing Nexus Staging features:
    [INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
    [INFO]
    [INFO] ------------------------------------------------------------------------
    [INFO] Building Jargon2 Native RI Backend 1.1.1
    [INFO] ------------------------------------------------------------------------
    [INFO]
    [INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ jargon2-native-ri-backend ---
    [INFO] com.kosprov.jargon2:jargon2-native-ri-backend:jar:1.1.1
    [INFO] +- com.nativelibs4java:jnaerator-runtime:jar:0.12:compile
    [INFO] |  +- com.nativelibs4java:ochafik-util:jar:0.12:compile
    [INFO] |  \- net.java.dev.jna:jna:jar:4.1.0:compile
    [INFO] \- com.kosprov.jargon2:jargon2-native-ri-binaries-generic:jar:1.1.1:runtime
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 2.808 s
    [INFO] Finished at: 2018-08-15T22:01:17+03:00
    [INFO] Final Memory: 23M/180M
    [INFO] ------------------------------------------------------------------------

**Comment by Darlio** [comment]
Hello, 

Works like a charm !!! I will now continue the HowTo !

One drawback though:
<-- We are looking for a very light implementation. With all dependencies, is it correct that we have -->
1. jargon2-api (48kb)
2. jargon2-native-ri-backend (19Kb)
3. jargon2-native-ri-binaries-generic (270Kb)
4. jna (1'450Kb)
5. jnaerator-runtime (44Kb)
6. ochafik-util (129Kb)
----------
1'910 Kb (which is also not that much either !)

CONCLUSION : This implementation rocks !!! And is easy to work with once it is set !
